version: '3.8'

services:
  financial-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Auth0__Domain=dev-87tccxbrltqxpenc.eu.auth0.com
      - Auth0__Audience=https://dev-87tccxbrltqxpenc.eu.auth0.com/api/v2/
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: gordey_kryzhanovskiy
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: financialdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
