using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

[Generator]
public class ModelGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var sourceCode = @"
        namespace GeneratedModels
        {
            public class AutoGeneratedModel
            {
                public int Id { get; set; }
                public string Name { get; set; }
            }
        }";

        context.AddSource("AutoGeneratedModel.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
    }
}
